version: '3.3'
services:
  spring-hibernate-frontend:
    container_name: spring-hibernate-frontend
    build:
      context: $HOME/spring-hibernate-frontend
      dockerfile: Dockerfile
    volumes:
    - '.:/spring-hibernate-frontend'
    - '/spring-hibernate-frontend/node_modules'
    ports:
    - 3000:3000
    environment:
    - NODE_ENV=production
    networks:
    - spring-hibernate-network
    depends_on:
    - spring-hibernate-backend
    restart: always
